name: Compilar LaTeX

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Compilar LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex # arquivo principal dentro da pasta working_directory
          working_directory: latex # define a pasta onde estão main.tex e CAPITULOS

      - name: Upload do PDF como artefato
        uses: actions/upload-artifact@v4
        with:
          name: PDF-gerado
          path: latex/main.pdf

      - name: Publicar no Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: latex/main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
